sidebars:
  type: objects
  default: []
  schema:
    name: "sidebar"
    identifier: name
    properties:
      name:
        type: string
        required: true
      category:
        type: categories
      tag:
        type: tags
      topic_id:
        type: integer
        required: true

sidebar_side:
  default: right
  type: enum
  choices:
    - left
    - right

inherit_parent_sidebar:
  default: true

stick_on_scroll:
  default: true
